//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_Llave
    {
        public int Codigo_Key { get; set; }
        public string Key_nmroCuenta_Folio { get; set; }
        public Nullable<int> NMRO_CUENTA_PPL { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> Cod_Envio { get; set; }
        public Nullable<int> Cod_Disparo { get; set; }
        public Nullable<int> Id_SNT { get; set; }
    }
}
