//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_VTR_paso
    {
        public int Codigo_Reg_VTRPaso { get; set; }
        public int Codigo_Reg_Valida { get; set; }
        public int Codigo_Reg_ValArchivo { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public string IDEN_CICLO { get; set; }
        public Nullable<int> IDEN_CICLO_ValType { get; set; }
        public string NMRO_CUENTA { get; set; }
        public Nullable<int> NMRO_CUENTA_ValType { get; set; }
        public string RUT_CUENTA { get; set; }
        public Nullable<int> RUT_CUENTA_ValType { get; set; }
        public string DESC_PATERNO { get; set; }
        public Nullable<int> DESC_PATERNO_ValType { get; set; }
        public string DESC_MATERNO { get; set; }
        public Nullable<int> DESC_MATERNO_ValType { get; set; }
        public string DESC_NOMBRES { get; set; }
        public Nullable<int> DESC_NOMBRES_ValType { get; set; }
        public string DESC_RAZSOC { get; set; }
        public Nullable<int> DESC_RAZSOC_ValType { get; set; }
        public string NMRO_CICLOFAC { get; set; }
        public Nullable<int> NMRO_CICLOFAC_ValType { get; set; }
        public string VLOR_DOCUMPRN { get; set; }
        public Nullable<int> VLOR_DOCUMPRN_ValType { get; set; }
        public string CODI_TIPDOCUM { get; set; }
        public Nullable<int> CODI_TIPDOCUM_ValType { get; set; }
        public string NMRO_EXTERNO { get; set; }
        public Nullable<int> NMRO_EXTERNO_ValType { get; set; }
        public string FECH_VENCMTO { get; set; }
        public Nullable<int> FECH_VENCMTO_ValType { get; set; }
        public string FECH_EMISION { get; set; }
        public Nullable<int> FECH_EMISION_ValType { get; set; }
        public string TIPO_RECEPCION { get; set; }
        public Nullable<int> TIPO_RECEPCION_ValType { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<int> CORREO_ELECTRONICO_ValType { get; set; }
        public string FECH_NACIM { get; set; }
        public Nullable<int> FECH_NACIM_ValType { get; set; }
        public string CODI_LOCALIDAD { get; set; }
        public Nullable<int> CODI_LOCALIDAD_ValType { get; set; }
        public string ESTD_PAC { get; set; }
        public Nullable<int> ESTD_PAC_ValType { get; set; }
        public string PACK_CONTRATADO { get; set; }
        public Nullable<int> PACK_CONTRATADO_ValType { get; set; }
        public string PIE_LINEA { get; set; }
        public Nullable<int> PIE_LINEA_ValType { get; set; }
        public string VLOR_DESCUENTOS_PROMOCIONALES { get; set; }
        public Nullable<int> VLOR_DESCUENTOS_PROMOCIONALES_ValType { get; set; }
        public string VLOR_SALDO_ANTERIOR { get; set; }
        public Nullable<int> VLOR_SALDO_ANTERIOR_ValType { get; set; }
        public string VLOR_COSTO_INST { get; set; }
        public Nullable<int> VLOR_COSTO_INST_ValType { get; set; }
        public string VLOR_ADICIONALES { get; set; }
        public Nullable<int> VLOR_ADICIONALES_ValType { get; set; }
        public string CLASESERVICIOS { get; set; }
        public Nullable<int> CLASESERVICIOS_ValType { get; set; }
        public string VLOR_PROPOR { get; set; }
        public Nullable<int> VLOR_PROPOR_ValType { get; set; }
        public string TIPO_CLIE { get; set; }
        public Nullable<int> TIPO_CLIE_ValType { get; set; }
        public string CODI_HTML { get; set; }
        public Nullable<int> CODI_HTML_ValType { get; set; }
        public string VLOR_SALDO_CUOTA_OTROS { get; set; }
        public Nullable<int> VLOR_SALDO_CUOTA_OTROS_ValType { get; set; }
        public string LOTE { get; set; }
        public Nullable<int> LOTE_ValType { get; set; }
        public string DIAS_PROPOR { get; set; }
        public Nullable<int> DIAS_PROPOR_ValType { get; set; }
        public string VLOR_PRODUCTO { get; set; }
        public Nullable<int> VLOR_PRODUCTO_ValType { get; set; }
        public string DESC_ACT { get; set; }
        public Nullable<int> DESC_ACT_ValType { get; set; }
        public string DESC_TOT { get; set; }
        public Nullable<int> DESC_TOT_ValType { get; set; }
    
        public virtual Boleta_VTR_VTR_valida Boleta_VTR_VTR_valida { get; set; }
    }
}
