//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_PPL_paso
    {
        public int Codigo_Reg_PPLPaso { get; set; }
        public Nullable<int> Codigo_Reg_Valida { get; set; }
        public Nullable<int> Codigo_Reg_ValArchivo { get; set; }
        public Nullable<int> Codigo_Reg_Proceso { get; set; }
        public string CorreoRecp { get; set; }
        public Nullable<int> CorreoRecp_ValType { get; set; }
        public string RutRecep { get; set; }
        public Nullable<int> RutRecep_ValType { get; set; }
        public string RznSocRecep { get; set; }
        public Nullable<int> RznSocRecep_ValType { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Contacto_ValType { get; set; }
        public string DirRecep { get; set; }
        public Nullable<int> DirRecep_ValType { get; set; }
        public string TpoDocRef { get; set; }
        public Nullable<int> TpoDocRef_ValType { get; set; }
        public string NumCtaPago { get; set; }
        public Nullable<int> NumCtaPago_ValType { get; set; }
        public string MntTotal { get; set; }
        public Nullable<int> MntTotal_ValType { get; set; }
        public string FchVenc { get; set; }
        public Nullable<int> FchVenc_ValType { get; set; }
        public string DocID_Detalle { get; set; }
        public Nullable<int> DocID_Detalle_ValType { get; set; }
        public string DocID_Boton { get; set; }
        public Nullable<int> DocID_Boton_ValType { get; set; }
        public string TipoFac { get; set; }
        public Nullable<int> TipoFac_ValType { get; set; }
        public string NMRO_CUENTA { get; set; }
        public Nullable<int> NMRO_CUENTA_ValType { get; set; }
        public string TipoDTE { get; set; }
        public Nullable<int> TipoDTE_ValType { get; set; }
        public string Folio { get; set; }
        public Nullable<int> Folio_ValType { get; set; }
        public string Contacto2 { get; set; }
        public Nullable<int> Contacto2_ValType { get; set; }
        public string XML { get; set; }
        public Nullable<int> XML_ValType { get; set; }
        public string PDF { get; set; }
        public Nullable<int> PDF_ValType { get; set; }
        public string Codigo_OT { get; set; }
    
        public virtual Boleta_VTR_PPL_valida Boleta_VTR_PPL_valida { get; set; }
    }
}
