//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_PPL_repeat
    {
        public int Codigo_Reg_PPLRepeat { get; set; }
        public int Codigo_Reg_Valida { get; set; }
        public Nullable<int> Codigo_Reg_ValArchivo { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public string CorreoRecp { get; set; }
        public string RutRecep { get; set; }
        public string RznSocRecep { get; set; }
        public string Contacto { get; set; }
        public string DirRecep { get; set; }
        public Nullable<int> TpoDocRef { get; set; }
        public Nullable<int> NumCtaPago { get; set; }
        public Nullable<int> MntTotal { get; set; }
        public Nullable<System.DateTime> FchVenc { get; set; }
        public string DocID_Detalle { get; set; }
        public string DocID_Boton { get; set; }
        public string TipoFac { get; set; }
        public Nullable<int> NMRO_CUENTA { get; set; }
        public string TipoDTE { get; set; }
        public Nullable<int> Folio { get; set; }
        public string Contacto2 { get; set; }
        public string XML { get; set; }
        public string PDF { get; set; }
        public Nullable<int> Codigo_OT { get; set; }
    }
}
