//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_OT_MuestrasVTR
    {
        public int Codigo_Reg_MuestraVTR { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public Nullable<int> Cod_Envio { get; set; }
        public Nullable<int> Codigo_OT { get; set; }
        public Nullable<int> Codi_HTML { get; set; }
        public Nullable<int> NMRO_CUENTA_PPL { get; set; }
        public Nullable<int> Folio { get; set; }
        public string CorreoRecp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
