//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_VTR_valida_archivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleta_VTR_VTR_valida_archivos()
        {
            this.Boleta_VTR_VTR_exclude = new HashSet<Boleta_VTR_VTR_exclude>();
            this.Boleta_VTR_VTR_valida = new HashSet<Boleta_VTR_VTR_valida>();
        }
    
        public int Codigo_Reg_ValArchivo { get; set; }
        public int Codigo_Reg_SWDEM { get; set; }
        public Nullable<int> Codigo_Reg_Proceso { get; set; }
        public string RutaCompleta { get; set; }
        public string Carpeta { get; set; }
        public string Fichero { get; set; }
        public Nullable<int> Codigo_Reg_EstadoCarga { get; set; }
        public string Desc_Carga { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public Nullable<int> Cantidad_Registros { get; set; }
        public Nullable<int> Cantidad_Reg_Exitosos { get; set; }
        public Nullable<int> Cantidad_Reg_Excluidos { get; set; }
        public Nullable<int> Cantidad_Reg_Insertados { get; set; }
        public Nullable<int> Cantidad_Reg_Repetidos { get; set; }
    
        public virtual Boleta_VTR_SWDEM Boleta_VTR_SWDEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta_VTR_VTR_exclude> Boleta_VTR_VTR_exclude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta_VTR_VTR_valida> Boleta_VTR_VTR_valida { get; set; }
    }
}
