//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_HTML
    {
        public int Cod_HTML { get; set; }
        public Nullable<int> Codigo_HTML { get; set; }
        public string HTML { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    }
}
