//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_VTR_PPL_clean
    {
        public int Cod_Envio { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public int Codigo_Reg_TipoServicio { get; set; }
        public int Codigo_Reg_VTRClean { get; set; }
        public Nullable<int> IDEN_CICLO { get; set; }
        public Nullable<int> NMRO_CUENTA_VTR { get; set; }
        public string RUT_CUENTA { get; set; }
        public string DESC_PATERNO { get; set; }
        public string DESC_MATERNO { get; set; }
        public string DESC_NOMBRES { get; set; }
        public string DESC_RAZSOC { get; set; }
        public Nullable<int> NMRO_CICLOFAC { get; set; }
        public Nullable<int> VLOR_DOCUMPRN { get; set; }
        public string CODI_TIPDOCUM { get; set; }
        public Nullable<int> NMRO_EXTERNO { get; set; }
        public Nullable<System.DateTime> FECH_VENCMTO { get; set; }
        public Nullable<System.DateTime> FECH_EMISION { get; set; }
        public string TIPO_RECEPCION { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<System.DateTime> FECH_NACIM { get; set; }
        public string CODI_LOCALIDAD { get; set; }
        public string ESTD_PAC { get; set; }
        public string PACK_CONTRATADO { get; set; }
        public string PIE_LINEA { get; set; }
        public Nullable<int> VLOR_DESCUENTOS_PROMOCIONALES { get; set; }
        public Nullable<int> VLOR_SALDO_ANTERIOR { get; set; }
        public Nullable<int> VLOR_COSTO_INST { get; set; }
        public Nullable<int> VLOR_ADICIONALES { get; set; }
        public string CLASESERVICIOS { get; set; }
        public Nullable<int> VLOR_PROPOR { get; set; }
        public string TIPO_CLIE { get; set; }
        public Nullable<int> CODI_HTML { get; set; }
        public Nullable<int> VLOR_SALDO_CUOTA_OTROS { get; set; }
        public string LOTE { get; set; }
        public Nullable<int> DIAS_PROPOR { get; set; }
        public Nullable<int> VLOR_PRODUCTO { get; set; }
        public Nullable<int> DESC_ACT { get; set; }
        public Nullable<int> DESC_TOT { get; set; }
        public int Codigo_Reg_PPLClean { get; set; }
        public string CorreoRecp { get; set; }
        public string RutRecep { get; set; }
        public string RznSocRecep { get; set; }
        public string Contacto { get; set; }
        public string DirRecep { get; set; }
        public Nullable<int> TpoDocRef { get; set; }
        public Nullable<int> NumCtaPago { get; set; }
        public Nullable<int> MntTotal { get; set; }
        public Nullable<System.DateTime> FchVenc { get; set; }
        public string DocID_Detalle { get; set; }
        public string DocID_Boton { get; set; }
        public string TipoFac { get; set; }
        public Nullable<int> NMRO_CUENTA_PPL { get; set; }
        public string TipoDTE { get; set; }
        public Nullable<int> Folio { get; set; }
        public string Contacto2 { get; set; }
        public string XML { get; set; }
        public string PDF { get; set; }
        public Nullable<int> Codigo_OT { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string FicheroPPL { get; set; }
        public Nullable<int> Disparo { get; set; }
    
        public virtual Boleta_VTR_PPL_clean Boleta_VTR_PPL_clean { get; set; }
        public virtual Boleta_VTR_VTR_clean Boleta_VTR_VTR_clean { get; set; }
    }
}
