//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_Disparo
    {
        public int Cod_Disparo { get; set; }
        public int Cod_Envio { get; set; }
        public string CorreoRecp { get; set; }
        public Nullable<int> NMRO_CUENTA_PPL { get; set; }
        public Nullable<int> Folio { get; set; }
        public string Subject { get; set; }
        public string HTML { get; set; }
        public string DOCID { get; set; }
        public Nullable<int> Codigo_OT { get; set; }
        public string PDF { get; set; }
        public string XML { get; set; }
        public string TipoDTE { get; set; }
        public string RutaYMD { get; set; }
        public Nullable<int> Codigo_Hilo { get; set; }
        public Nullable<int> Enviado { get; set; }
        public Nullable<System.DateTime> FechaEnviado { get; set; }
        public string ResultEnvio { get; set; }
        public string Detalle { get; set; }
    }
}
