//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_OT_MuestrasR3
    {
        public int Codigo_Reg_MuestraR3 { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public int Cod_Envio { get; set; }
        public int Codigo_OT { get; set; }
        public int Codi_HTML { get; set; }
        public string URL_VerDetalle { get; set; }
        public Nullable<int> URL_VerDetalle_VAL { get; set; }
        public string URL_BotonPago { get; set; }
        public Nullable<int> URL_BotonPago_VAL { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
