//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_PPL_Carga
    {
        public int Codigo_Reg_CargaPPL { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public Nullable<int> Codigo_Reg_OT { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string CarpetaPPL { get; set; }
        public string FicheroPPL { get; set; }
        public Nullable<System.DateTime> FechaCargaPPL { get; set; }
        public string ResultCargaPPL { get; set; }
        public string CodResultCargaPPL { get; set; }
        public Nullable<int> CantRegistrosCargaPPL { get; set; }
        public string DetalleError { get; set; }
        public Nullable<System.DateTime> FechaProcVTRPPL { get; set; }
        public Nullable<int> ProcVTRPPL { get; set; }
        public Nullable<int> CantRegistrosVTRPPL { get; set; }
        public Nullable<System.DateTime> FechaProcDisparoInicio { get; set; }
        public Nullable<System.DateTime> FechaProcDisparoFin { get; set; }
        public Nullable<int> ProcDisparo { get; set; }
        public Nullable<int> CantRegistrosDisparo { get; set; }
        public Nullable<System.DateTime> FechaProcEnviosInicio { get; set; }
        public Nullable<System.DateTime> FechaProcEnviosFin { get; set; }
        public Nullable<int> CantRegistrosEnviados { get; set; }
        public Nullable<int> CantRegistrosEnv_E { get; set; }
        public Nullable<int> CantRegistrosEnv_F { get; set; }
        public Nullable<int> ProcEnvio { get; set; }
    
        public virtual Boleta_VTR_OT Boleta_VTR_OT { get; set; }
        public virtual Boleta_VTR_Procesos Boleta_VTR_Procesos { get; set; }
    }
}
