//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_Agenda_Job
    {
        public int Codigo_Job { get; set; }
        public int Codigo_Reg_SWDEM { get; set; }
        public Nullable<int> Codigo_Reg_Proceso { get; set; }
        public string Ruta_Archivo { get; set; }
        public string Desc_job { get; set; }
        public string Nombre_SP { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public Nullable<System.DateTime> Fec_planificacion_ejecucion { get; set; }
        public Nullable<System.DateTime> Fec_inicio_ejecucion { get; set; }
        public Nullable<System.DateTime> Fec_termino_ejecucion { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Boleta_VTR_Procesos Boleta_VTR_Procesos { get; set; }
        public virtual Boleta_VTR_SWDEM Boleta_VTR_SWDEM { get; set; }
    }
}
