//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_PPL_clean
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleta_VTR_PPL_clean()
        {
            this.Boleta_VTR_VTR_PPL_clean = new HashSet<Boleta_VTR_VTR_PPL_clean>();
        }
    
        public int Codigo_Reg_PPLClean { get; set; }
        public int Codigo_Reg_Valida { get; set; }
        public Nullable<int> Codigo_Reg_ValArchivo { get; set; }
        public int Codigo_Reg_Proceso { get; set; }
        public string CorreoRecp { get; set; }
        public string RutRecep { get; set; }
        public string RznSocRecep { get; set; }
        public string Contacto { get; set; }
        public string DirRecep { get; set; }
        public Nullable<int> TpoDocRef { get; set; }
        public Nullable<int> NumCtaPago { get; set; }
        public Nullable<int> MntTotal { get; set; }
        public Nullable<System.DateTime> FchVenc { get; set; }
        public string DocID_Detalle { get; set; }
        public string DocID_Boton { get; set; }
        public string TipoFac { get; set; }
        public Nullable<int> NMRO_CUENTA { get; set; }
        public string TipoDTE { get; set; }
        public Nullable<int> Folio { get; set; }
        public string Contacto2 { get; set; }
        public string XML { get; set; }
        public string PDF { get; set; }
        public Nullable<int> Codigo_OT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta_VTR_VTR_PPL_clean> Boleta_VTR_VTR_PPL_clean { get; set; }
    }
}
