//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_Alta_OT
    {
        public int Codigo_Reg_Alta { get; set; }
        public int Codigo_Reg_OT { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Boleta_VTR_OT Boleta_VTR_OT { get; set; }
    }
}
