//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta_VTR_OT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleta_VTR_OT()
        {
            this.Boleta_VTR_Alta_OT = new HashSet<Boleta_VTR_Alta_OT>();
            this.Boleta_VTR_PPL_Carga = new HashSet<Boleta_VTR_PPL_Carga>();
        }
    
        public int Codigo_Reg_OT { get; set; }
        public Nullable<int> Codigo_Estado_ProcOT { get; set; }
        public Nullable<int> Codigo_Reg_Proceso { get; set; }
        public int Codigo_OT { get; set; }
        public Nullable<int> Iden_ciclo { get; set; }
        public Nullable<decimal> Folio_Inicio { get; set; }
        public Nullable<decimal> Folio_Fin { get; set; }
        public Nullable<System.DateTime> Fec_Lote { get; set; }
        public string Tipo_documento { get; set; }
        public Nullable<int> Numero_documentos { get; set; }
        public Nullable<int> Correcccion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaHora_Disparo { get; set; }
        public Nullable<int> Programacion_Global { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta_VTR_Alta_OT> Boleta_VTR_Alta_OT { get; set; }
        public virtual Boleta_VTR_OT_estado Boleta_VTR_OT_estado { get; set; }
        public virtual Boleta_VTR_Procesos Boleta_VTR_Procesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleta_VTR_PPL_Carga> Boleta_VTR_PPL_Carga { get; set; }
    }
}
