//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltrosQueryBuilder
    {
        public int IdFiltro { get; set; }
        public string Id { get; set; }
        public string Field { get; set; }
        public string Label { get; set; }
        public string Optgroup { get; set; }
        public string Type { get; set; }
        public string Input { get; set; }
        public string Valuess { get; set; }
        public string Default_value { get; set; }
        public string Input_event { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<bool> Multiple { get; set; }
        public string Placeholder { get; set; }
        public Nullable<bool> Vertical { get; set; }
        public string Validation { get; set; }
        public string Operators { get; set; }
        public string Plugin { get; set; }
        public string Plugin_config { get; set; }
        public string Data { get; set; }
        public string ValueSetter { get; set; }
        public string ValueGetter { get; set; }
        public int Orden { get; set; }
        public bool ValueFromDb { get; set; }
    }
}
