//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatablesCheckBox.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerBi_Disparos
    {
        public Nullable<int> Llave { get; set; }
        public int Codigo_Carga { get; set; }
        public Nullable<System.DateTime> FechaCiclo { get; set; }
        public string FicheroVTR { get; set; }
        public Nullable<int> NMRO_CICLOFAC { get; set; }
        public string FechaRecepDoc { get; set; }
        public Nullable<int> Total { get; set; }
        public string Negocio { get; set; }
        public string TipoFichero { get; set; }
        public string FechaEnvioDoc { get; set; }
    }
}
